### ISSUE TITLE
REST API of Server

### ISSUE THREAD

**Issue by joelmanx** [sytolk/TaxiAndroidOpen#11]
Which is the schema of the API REST? for to build the Backend

**Comment by sytolk** [comment]
API Rest service is not open source sorry

**Comment by joelmanx** [comment]
okey, but just I need the structure, please

**Comment by sytolk** [comment]
You can try to decompile Pojos model. It is generated from backend DB schema structure
https://oss.sonatype.org/content/repositories/snapshots/com/taxi-bulgaria/rest/pojos/1.0.5-SNAPSHOT/pojos-1.0.5-20170624.082239-11.jar

http://www.javadecompilers.com/

**Comment by joelmanx** [comment]
thanks!
