### ISSUE TITLE
Migrating project

### ISSUE THREAD

**Issue by kkoci** [sytolk/TaxiAndroidOpen#8]
Hi, I'm migrating the project to AndroidStudio

I managed to install some of the dependencies, but there are some things I'd like to understand better, I hope you can help me.

When you say:

import com.taxibulgaria.enums.RegionsType;

What is exactly 'import com.taxibulgaria...'? I suppose this is a package, right?

Since I'm migrating everything to gradle, I'm a little bit confused about this, is this an alias stated on the pom.xml maven file?

On the other hand when you declare this:

import org.mapsforge.applications.android.LocationOverlayMapViewer;

This is the same path as the Sample application you can find on mapsforge github:

https://github.com/mapsforge/mapsforge/tree/master/Applications/Android/Samples

Of course, AndroidStudio cannot resolve these paths because they don't exist in the local project, but since I'm using gradle almost from scratch, maybe I'm missing something here, some 'alias' stated on pom.xml or something.

I hope I've explained myself, Thanks in advance!

**Comment by sytolk** [comment]
Its need to include maven dependency in gradle project. Gradle include it from maven central repo. Take a look in this project:
https://github.com/mcharmas/Android-ReactiveLocation?files=1

**Comment by sytolk** [comment]
Maven and Gradle are automaticaly build systems - downoload all dependency and build project. You can try to convert pom.xml file to gradle.build with 
gradle init --type pom 
https://docs.gradle.org/current/userguide/build_init_plugin.html

**Comment by kkoci** [comment]
Awesome, let me try, I waas adding some .jars and dependencies on app's buld.gradle from scratch but I have these few issues, let me try

**Comment by sytolk** [comment]
Its have Gradle build now
https://github.com/sytolk/TaxiAndroidOpen/commit/85e46cfa8b8412f22c0f6367cd04fa575ceb6b2b

**Comment by kkoci** [comment]
Awesome @sytolk , going to check it ASAP
